version: '3.7'

services:
  ctflightinfo:
    image: ctflightinfo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    links:
      - redis
    networks:
      - node-webapp-network
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
    networks:
      - node-webapp-network
networks:
    node-webapp-network:
        name: weatherapi
        driver: bridge